import React from 'react';

export function AboutUs() {
  return (
    <div className="max-w-3xl mx-auto py-16 px-4 sm:px-6 lg:px-8 animate-in fade-in duration-500">
      <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-6">About Us</h1>
      <div className="prose dark:prose-invert text-slate-600 dark:text-slate-300 space-y-4">
        <p>Welcome to Vision AI Calculator, your all-in-one platform for precise calculations, comprehensive unit conversions, and intelligent problem-solving.</p>
        <p>Our mission is to simplify complex mathematical and everyday calculations by providing a clean, fast, and accessible tool for everyone—from students and professionals to everyday users.</p>
        <p>Powered by advanced AI technology, we aim to bridge the gap between traditional calculators and natural language understanding, making math more intuitive than ever.</p>
      </div>
    </div>
  );
}

export function TermsConditions() {
  return (
    <div className="max-w-3xl mx-auto py-16 px-4 sm:px-6 lg:px-8 animate-in fade-in duration-500">
      <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-6">Terms & Conditions</h1>
      <div className="prose dark:prose-invert text-slate-600 dark:text-slate-300 space-y-4">
        <p>By accessing and using Vision AI Calculator, you accept and agree to be bound by the terms and provision of this agreement.</p>
        <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-6">Use of Service</h2>
        <p>Our tools are provided "as is" for informational and educational purposes. While we strive for accuracy, we do not guarantee the absolute correctness of any calculation or conversion.</p>
        <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-6">AI Responses</h2>
        <p>The AI Text Calculator uses third-party APIs (Google Gemini). Responses are generated by AI and should be verified independently for critical applications.</p>
      </div>
    </div>
  );
}

export function PrivacyPolicy() {
  return (
    <div className="max-w-3xl mx-auto py-16 px-4 sm:px-6 lg:px-8 animate-in fade-in duration-500">
      <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-6">Privacy Policy</h1>
      <div className="prose dark:prose-invert text-slate-600 dark:text-slate-300 space-y-4">
        <p>Your privacy is important to us. This policy explains how we handle your data when you use Vision AI Calculator.</p>
        <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-6">Data Collection</h2>
        <p>We do not require user accounts or authentication. We may log AI queries anonymously to improve our service and monitor usage limits.</p>
        <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-6">Cookies and Ads</h2>
        <p>We use third-party advertising partners (like Google AdSense) who may use cookies to serve ads based on your prior visits to our website or other websites.</p>
      </div>
    </div>
  );
}
